services:
  libredb_studio:
    image: libredb/libredb-studio:${VERSION}
    ports:
      - "${HOST_IP}:${LIBREDB_STUDIO_WEB_PORT}:3000"
    environment:
      - STORAGE_PROVIDER=sqlite
      - STORAGE_SQLITE_PATH=/app/data/libredb-storage.db
    volumes:
      - ${APP_PATH}/data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
